# Project configuiration options for Python tools.
[tool.black] # https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
target-version = ["py310"]
line-length = 120

[tool.isort] # https://pycqa.github.io/isort/docs/configuration/options.html
py_version = "310"
line_length = 120
profile = "black"
skip_gitignore = true

[tool.mypy] # https://mypy.readthedocs.io/en/stable/config_file.html
python_version = "3.10"
warn_unused_configs = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = false     # Some calls from NumPy are untyped.
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
strict_equality = true
